'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Football1

    '''<summary>
    '''cboClass control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboClass As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''cboGame0101 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboGame0101 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''validateScoresheet0101 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents validateScoresheet0101 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''cboGame0102 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboGame0102 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''validateScoresheet0102 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents validateScoresheet0102 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''cboGame0201 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboGame0201 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''RequiredFieldValidator0201 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidator0201 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''cboGame0202 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboGame0202 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''RequiredFieldValidator0202 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidator0202 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''cboGame0301 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboGame0301 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''RequiredFieldValidator0301 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidator0301 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''cboGame0302 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboGame0302 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''RequiredFieldValidator0302 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidator0302 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''cboGame0401 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboGame0401 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''RequiredFieldValidator0401 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidator0401 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''cboGame0402 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboGame0402 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''RequiredFieldValidator0402 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidator0402 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''cboGame0501 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboGame0501 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''RequiredFieldValidator0501 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidator0501 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''cboGame0502 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboGame0502 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''RequiredFieldValidator0502 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidator0502 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''cboGame0601 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboGame0601 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''RequiredFieldValidator0601 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidator0601 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''cboGame0602 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboGame0602 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''RequiredFieldValidator0602 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidator0602 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''cboGame0701 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboGame0701 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''RequiredFieldValidator0701 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidator0701 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''cboGame0702 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboGame0702 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''RequiredFieldValidator0702 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidator0702 As Global.System.Web.UI.WebControls.RequiredFieldValidator
End Class
