'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class PlayoffScores

	'''<summary>
	'''form1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

	'''<summary>
	'''RadAjaxPanel1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents RadAjaxPanel1 As Global.Telerik.Web.UI.RadAjaxPanel

	'''<summary>
	'''tblPlayoffs control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents tblPlayoffs As Global.System.Web.UI.WebControls.Table

	'''<summary>
	'''RadDropDownListYear control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents RadDropDownListYear As Global.Telerik.Web.UI.RadDropDownList

	'''<summary>
	'''txtDate control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtDate As Global.Telerik.Web.UI.RadTextBox

	'''<summary>
	'''RadDropDownListDay control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents RadDropDownListDay As Global.Telerik.Web.UI.RadDropDownList

	'''<summary>
	'''RadDropDownListSport control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents RadDropDownListSport As Global.Telerik.Web.UI.RadDropDownList

	'''<summary>
	'''RadDropDownListClass control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents RadDropDownListClass As Global.Telerik.Web.UI.RadDropDownList

	'''<summary>
	'''RadDropDownListLevel control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents RadDropDownListLevel As Global.Telerik.Web.UI.RadDropDownList

	'''<summary>
	'''RadDropDownListRound control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents RadDropDownListRound As Global.Telerik.Web.UI.RadDropDownList

	'''<summary>
	'''RadAutoCompleteBoxLocation control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents RadAutoCompleteBoxLocation As Global.Telerik.Web.UI.RadAutoCompleteBox

	'''<summary>
	'''RadDropDownRegionalNumber control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents RadDropDownRegionalNumber As Global.Telerik.Web.UI.RadDropDownList

	'''<summary>
	'''lblWinner control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblWinner As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''RadAutoCompleteBoxWinner control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents RadAutoCompleteBoxWinner As Global.Telerik.Web.UI.RadAutoCompleteBox

	'''<summary>
	'''txtWinnerScore control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtWinnerScore As Global.Telerik.Web.UI.RadTextBox

	'''<summary>
	'''Label1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''lblLoser control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblLoser As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''RadAutoCompleteBoxLoser control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents RadAutoCompleteBoxLoser As Global.Telerik.Web.UI.RadAutoCompleteBox

	'''<summary>
	'''txtLoserScore control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtLoserScore As Global.Telerik.Web.UI.RadTextBox

	'''<summary>
	'''lblOT control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblOT As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''txtOT control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtOT As Global.Telerik.Web.UI.RadTextBox

	'''<summary>
	'''lblOTa control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblOTa As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''cmdSave control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents cmdSave As Global.Telerik.Web.UI.RadButton

	'''<summary>
	'''lblMessage control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblMessage As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''RadGrid1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents RadGrid1 As Global.Telerik.Web.UI.RadGrid

	'''<summary>
	'''SqlDataSourceLocations control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents SqlDataSourceLocations As Global.System.Web.UI.WebControls.SqlDataSource

	'''<summary>
	'''SqlDataSourceYears control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents SqlDataSourceYears As Global.System.Web.UI.WebControls.SqlDataSource

	'''<summary>
	'''SqlDataSourceSchools control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents SqlDataSourceSchools As Global.System.Web.UI.WebControls.SqlDataSource

	'''<summary>
	'''SqlDataSourceResults control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents SqlDataSourceResults As Global.System.Web.UI.WebControls.SqlDataSource
End Class
