'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class FBFlashback
    
    '''<summary>
    '''RadAjaxPanel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAjaxPanel2 As Global.Telerik.Web.UI.RadAjaxPanel
    
    '''<summary>
    '''RadPageLayout1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadPageLayout1 As Global.Telerik.Web.UI.RadPageLayout
    
    '''<summary>
    '''lblOneColumnHeader0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOneColumnHeader0 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblOneColumnDetail0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOneColumnDetail0 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblOneColumnHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOneColumnHeader As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblOneColumnDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOneColumnDetail As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''RadPageLayout2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadPageLayout2 As Global.Telerik.Web.UI.RadPageLayout
    
    '''<summary>
    '''Label1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblCurrentWeek control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCurrentWeek As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblDistrictStandings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDistrictStandings As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''hlDist6A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlDist6A As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''hlDist5A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlDist5A As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''hlDist4A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlDist4A As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''hlDist3A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlDist3A As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''hlDist2A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlDist2A As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''hlDistA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlDistA As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''hlDistB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlDistB As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''hlDistC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlDistC As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''hlBlog1999 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlBlog1999 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''hlWeek01 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlWeek01 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''hlWeek02 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlWeek02 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''hlWeek03 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlWeek03 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''hlWeek04 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlWeek04 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''hlWeek05 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlWeek05 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''hlWeek06 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlWeek06 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''hlWeek07 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlWeek07 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''hlWeek08 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlWeek08 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''hlWeek09 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlWeek09 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''hlWeek10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlWeek10 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''hlPlayoffs1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlPlayoffs1 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''hlPlayoffs2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlPlayoffs2 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''hlPlayoffs3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlPlayoffs3 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''hlPlayoffs4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlPlayoffs4 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''hlPlayoffs5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlPlayoffs5 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''lblScheduleHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScheduleHeader As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''imgSponsor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgSponsor As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''tblContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblContent As Global.System.Web.UI.WebControls.Table
    
    '''<summary>
    '''rowSchedule control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowSchedule As Global.System.Web.UI.WebControls.TableRow
    
    '''<summary>
    '''RadGridSchedule6A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadGridSchedule6A As Global.Telerik.Web.UI.RadGrid
    
    '''<summary>
    '''RadGridSchedule5A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadGridSchedule5A As Global.Telerik.Web.UI.RadGrid
    
    '''<summary>
    '''RadGridSchedule4A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadGridSchedule4A As Global.Telerik.Web.UI.RadGrid
    
    '''<summary>
    '''RadGridSchedule3A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadGridSchedule3A As Global.Telerik.Web.UI.RadGrid
    
    '''<summary>
    '''RadGridSchedule2A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadGridSchedule2A As Global.Telerik.Web.UI.RadGrid
    
    '''<summary>
    '''RadGridScheduleA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadGridScheduleA As Global.Telerik.Web.UI.RadGrid
    
    '''<summary>
    '''RadGridScheduleB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadGridScheduleB As Global.Telerik.Web.UI.RadGrid
    
    '''<summary>
    '''RadGridScheduleC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadGridScheduleC As Global.Telerik.Web.UI.RadGrid
    
    '''<summary>
    '''rowDistricts1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowDistricts1 As Global.System.Web.UI.WebControls.TableRow
    
    '''<summary>
    '''RadGridDistrict1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadGridDistrict1 As Global.Telerik.Web.UI.RadGrid
    
    '''<summary>
    '''rowDistricts2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowDistricts2 As Global.System.Web.UI.WebControls.TableRow
    
    '''<summary>
    '''RadGridDistrict2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadGridDistrict2 As Global.Telerik.Web.UI.RadGrid
    
    '''<summary>
    '''rowDistricts3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowDistricts3 As Global.System.Web.UI.WebControls.TableRow
    
    '''<summary>
    '''RadGridDistrict3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadGridDistrict3 As Global.Telerik.Web.UI.RadGrid
    
    '''<summary>
    '''rowDistricts4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowDistricts4 As Global.System.Web.UI.WebControls.TableRow
    
    '''<summary>
    '''RadGridDistrict4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadGridDistrict4 As Global.Telerik.Web.UI.RadGrid
    
    '''<summary>
    '''rowDistricts5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowDistricts5 As Global.System.Web.UI.WebControls.TableRow
    
    '''<summary>
    '''RadGridDistrict5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadGridDistrict5 As Global.Telerik.Web.UI.RadGrid
    
    '''<summary>
    '''rowDistricts6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowDistricts6 As Global.System.Web.UI.WebControls.TableRow
    
    '''<summary>
    '''RadGridDistrict6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadGridDistrict6 As Global.Telerik.Web.UI.RadGrid
    
    '''<summary>
    '''rowDistricts7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowDistricts7 As Global.System.Web.UI.WebControls.TableRow
    
    '''<summary>
    '''RadGridDistrict7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadGridDistrict7 As Global.Telerik.Web.UI.RadGrid
    
    '''<summary>
    '''rowDistricts8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowDistricts8 As Global.System.Web.UI.WebControls.TableRow
    
    '''<summary>
    '''RadGridDistrict8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadGridDistrict8 As Global.Telerik.Web.UI.RadGrid
End Class
