'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class PlayoffCentralBK
    
    '''<summary>
    '''RadAjaxPanel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAjaxPanel2 As Global.Telerik.Web.UI.RadAjaxPanel
    
    '''<summary>
    '''RadPageLayout1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadPageLayout1 As Global.Telerik.Web.UI.RadPageLayout
    
    '''<summary>
    '''lblOneColumnHeader0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOneColumnHeader0 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblOneColumnDetail0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOneColumnDetail0 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblOneColumnHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOneColumnHeader As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblOneColumnDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOneColumnDetail As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''RadAjaxPanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAjaxPanel1 As Global.Telerik.Web.UI.RadAjaxPanel
    
    '''<summary>
    '''RadPageLayout2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadPageLayout2 As Global.Telerik.Web.UI.RadPageLayout
    
    '''<summary>
    '''cboClass control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboClass As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lblHeaderBoys control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHeaderBoys As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tblPlayoffCentralBK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblPlayoffCentralBK As Global.System.Web.UI.WebControls.Table
    
    '''<summary>
    '''row1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents row1 As Global.System.Web.UI.WebControls.TableRow
    
    '''<summary>
    '''cellR1C1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR1C1 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''cellR1C2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR1C2 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''cellR1C3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR1C3 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''cellR1C4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR1C4 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''cellR1C5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR1C5 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''row2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents row2 As Global.System.Web.UI.WebControls.TableRow
    
    '''<summary>
    '''cellR2C1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR2C1 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''cellR2C2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR2C2 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''lblR2C2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblR2C2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''imgR2C2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgR2C2 As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''PopupControlExtenderR2C2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PopupControlExtenderR2C2 As Global.AjaxControlToolkit.PopupControlExtender
    
    '''<summary>
    '''cellR2C3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR2C3 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''lblR2C3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblR2C3 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''imgR2C3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgR2C3 As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''cellR2C4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR2C4 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''lblR2C4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblR2C4 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''imgR2C4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgR2C4 As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''cellR2C5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR2C5 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''lblR2C5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblR2C5 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''imgR2C5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgR2C5 As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''row3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents row3 As Global.System.Web.UI.WebControls.TableRow
    
    '''<summary>
    '''cellR3C1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR3C1 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''cellR3C2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR3C2 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''lblR3C2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblR3C2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''imgR3C2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgR3C2 As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''cellR3C3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR3C3 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''lblR3C3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblR3C3 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''imgR3C3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgR3C3 As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''cellR3C4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR3C4 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''lblR3C4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblR3C4 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''imgR3C4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgR3C4 As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''cellR3C5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR3C5 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''lblR3C5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblR3C5 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''imgR3C5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgR3C5 As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''row4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents row4 As Global.System.Web.UI.WebControls.TableRow
    
    '''<summary>
    '''cellR4C1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR4C1 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''cellR4C2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR4C2 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''lblR4C2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblR4C2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''imgR4C2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgR4C2 As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''cellR4C3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR4C3 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''lblR4C3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblR4C3 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''imgR4C3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgR4C3 As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''cellR4C4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR4C4 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''lblR4C4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblR4C4 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''imgR4C4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgR4C4 As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''cellR4C5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR4C5 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''lblR4C5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblR4C5 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''imgR4C5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgR4C5 As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''row5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents row5 As Global.System.Web.UI.WebControls.TableRow
    
    '''<summary>
    '''cellR5C1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR5C1 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''cellR5C2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR5C2 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''lblR5C2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblR5C2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''imgR5C2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgR5C2 As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''cellR5C3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR5C3 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''lblR5C3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblR5C3 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''imgR5C3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgR5C3 As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''cellR5C4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR5C4 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''lblR5C4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblR5C4 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''imgR5C4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgR5C4 As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''cellR5C5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR5C5 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''lblR5C5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblR5C5 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''imgR5C5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgR5C5 As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''lblHeaderGirls control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHeaderGirls As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tblPlayoffCentralBK2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblPlayoffCentralBK2 As Global.System.Web.UI.WebControls.Table
    
    '''<summary>
    '''row6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents row6 As Global.System.Web.UI.WebControls.TableRow
    
    '''<summary>
    '''cellR6C1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR6C1 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''cellR6C2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR6C2 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''cellR6C3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR6C3 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''cellR6C4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR6C4 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''cellR6C5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR6C5 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''row7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents row7 As Global.System.Web.UI.WebControls.TableRow
    
    '''<summary>
    '''cellR7C1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR7C1 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''cellR7C2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR7C2 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''lblR7C2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblR7C2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''imgR7C2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgR7C2 As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''cellR7C3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR7C3 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''lblR7C3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblR7C3 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''imgR7C3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgR7C3 As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''cellR7C4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR7C4 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''lblR7C4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblR7C4 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''imgR7C4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgR7C4 As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''cellR7C5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR7C5 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''lblR7C5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblR7C5 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''imgR7C5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgR7C5 As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''row8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents row8 As Global.System.Web.UI.WebControls.TableRow
    
    '''<summary>
    '''cellR8C1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR8C1 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''cellR8C2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR8C2 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''lblR8C2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblR8C2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''imgR8C2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgR8C2 As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''cellR8C3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR8C3 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''lblR8C3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblR8C3 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''imgR8C3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgR8C3 As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''cellR8C4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR8C4 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''lblR8C4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblR8C4 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''imgR8C4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgR8C4 As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''cellR8C5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR8C5 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''lblR8C5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblR8C5 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''imgR8C5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgR8C5 As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''row9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents row9 As Global.System.Web.UI.WebControls.TableRow
    
    '''<summary>
    '''cellR9C1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR9C1 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''cellR9C2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR9C2 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''lblR9C2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblR9C2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''imgR9C2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgR9C2 As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''cellR9C3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR9C3 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''lblR9C3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblR9C3 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''imgR9C3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgR9C3 As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''cellR9C4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR9C4 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''lblR9C4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblR9C4 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''imgR9C4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgR9C4 As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''cellR9C5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR9C5 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''lblR9C5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblR9C5 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''imgR9C5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgR9C5 As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''row10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents row10 As Global.System.Web.UI.WebControls.TableRow
    
    '''<summary>
    '''cellR10C1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR10C1 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''cellR10C2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR10C2 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''lblR10C2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblR10C2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''imgR10C2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgR10C2 As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''cellR10C3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR10C3 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''lblR10C3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblR10C3 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''imgR10C3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgR10C3 As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''cellR10C4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR10C4 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''lblR10C4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblR10C4 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''imgR10C4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgR10C4 As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''cellR10C5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR10C5 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''lblR10C5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblR10C5 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''imgR10C5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgR10C5 As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''PanelPopup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelPopup As Global.System.Web.UI.WebControls.Panel
End Class
