'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class PlayoffCentralBA
    
    '''<summary>
    '''RadAjaxPanelMOBILE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAjaxPanelMOBILE As Global.Telerik.Web.UI.RadAjaxPanel
    
    '''<summary>
    '''RadPageLayout1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadPageLayout1 As Global.Telerik.Web.UI.RadPageLayout
    
    '''<summary>
    '''lblHeaderBoysM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHeaderBoysM As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblHeaderBoys1M control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHeaderBoys1M As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Label3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label3 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cboClassm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboClassm As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''cellQFm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellQFm As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''hlR1C1m control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlR1C1m As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''hlR1C2m control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlR1C2m As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''hlR2C1m control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlR2C1m As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''hlR2C2m control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlR2C2m As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''hlR3C1m control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlR3C1m As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''hlR3C2m control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlR3C2m As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''hlR4C1m control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlR4C1m As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''hlR4C2m control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlR4C2m As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''hlR5C1m control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlR5C1m As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''hlR5C2m control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlR5C2m As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''hlR6C1m control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlR6C1m As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''hlR6C2m control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlR6C2m As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''hlR7C1m control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlR7C1m As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''hlR7C2m control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlR7C2m As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''hlR8C1m control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlR8C1m As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''hlR8C2m control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlR8C2m As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''hlR9C1m control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlR9C1m As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''hlR9C2m control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlR9C2m As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''hlR10C1m control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlR10C1m As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''hlR10C2m control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlR10C2m As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''hlR11C1m control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlR11C1m As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''hlR11C2m control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlR11C2m As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''hlR12C1m control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlR12C1m As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''hlR12C2m control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlR12C2m As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Label4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label4 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''hlR13C1m control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlR13C1m As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''hlR13C2m control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlR13C2m As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''hlR14C1m control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlR14C1m As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''hlR14C2m control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlR14C2m As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblTeam1SeasonInfoM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTeam1SeasonInfoM As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''RadGridTeamSeasonM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadGridTeamSeasonM As Global.Telerik.Web.UI.RadGrid
    
    '''<summary>
    '''lblTeam2SeasonInfoM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTeam2SeasonInfoM As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''RadGridTeamHistoryM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadGridTeamHistoryM As Global.Telerik.Web.UI.RadGrid
    
    '''<summary>
    '''hlBottomM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlBottomM As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''RadAjaxPanelWEB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAjaxPanelWEB As Global.Telerik.Web.UI.RadAjaxPanel
    
    '''<summary>
    '''tblHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblHeader As Global.System.Web.UI.WebControls.Table
    
    '''<summary>
    '''cboClass control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboClass As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''tblContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblContent As Global.System.Web.UI.WebControls.Table
    
    '''<summary>
    '''lblHeaderBoys control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHeaderBoys As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblHeaderBoys1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHeaderBoys1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblNote control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNote As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''hlShowBracket control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlShowBracket As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''tblPlayoffCentralBA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblPlayoffCentralBA As Global.System.Web.UI.WebControls.Table
    
    '''<summary>
    '''hlState control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlState As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''hlNews control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlNews As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''row1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents row1 As Global.System.Web.UI.WebControls.TableRow
    
    '''<summary>
    '''cellR1C1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR1C1 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''cellR1C2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR1C2 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''cellR1C3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR1C3 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''cellR1C4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR1C4 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''cellR1C5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR1C5 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''cellR1C6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR1C6 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''cellR1C7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR1C7 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''row2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents row2 As Global.System.Web.UI.WebControls.TableRow
    
    '''<summary>
    '''cellR2C1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR2C1 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''hlR2C1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlR2C1 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''cellR2C2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR2C2 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''hlR2C2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlR2C2 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''cellR2C3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR2C3 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''hlR2C3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlR2C3 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''cellR2C4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR2C4 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''hlR2C4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlR2C4 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''cellR2C5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR2C5 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''hlR2C5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlR2C5 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''cellR2C6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR2C6 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''hlR2C6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlR2C6 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''cellR2C7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR2C7 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''hlR2C7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlR2C7 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''row3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents row3 As Global.System.Web.UI.WebControls.TableRow
    
    '''<summary>
    '''cellR3C1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR3C1 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''hlR3C1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlR3C1 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''cellR3C2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR3C2 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''hlR3C2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlR3C2 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''cellR3C3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR3C3 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''hlR3C3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlR3C3 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''cellR3C4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR3C4 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''hlR3C4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlR3C4 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''cellR3C5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR3C5 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''hlR3C5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlR3C5 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''cellR3C6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR3C6 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''hlR3C6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlR3C6 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''cellR3C7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR3C7 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''hlR3C7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlR3C7 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''row4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents row4 As Global.System.Web.UI.WebControls.TableRow
    
    '''<summary>
    '''cellR4C1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR4C1 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''hlR4C1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlR4C1 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''cellR4C2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR4C2 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''hlR4C2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlR4C2 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''cellR4C3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR4C3 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''hlR4C3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlR4C3 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''cellR4C4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR4C4 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''hlR4C4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlR4C4 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''cellR4C5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR4C5 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''hlR4C5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlR4C5 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''cellR4C6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR4C6 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''hlR4C6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlR4C6 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''cellR4C7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR4C7 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''hlR4C7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlR4C7 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''row5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents row5 As Global.System.Web.UI.WebControls.TableRow
    
    '''<summary>
    '''cellR5C1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR5C1 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''hlR5C1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlR5C1 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''cellR5C2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR5C2 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''hlR5C2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlR5C2 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''cellR5C3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR5C3 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''hlR5C3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlR5C3 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''cellR5C4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR5C4 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''hlR5C4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlR5C4 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''cellR5C5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR5C5 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''hlR5C5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlR5C5 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''cellR5C6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR5C6 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''hlR5C6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlR5C6 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''cellR5C7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR5C7 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''hlR5C7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlR5C7 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''row6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents row6 As Global.System.Web.UI.WebControls.TableRow
    
    '''<summary>
    '''cellR6C1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR6C1 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''hlR6C1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlR6C1 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''cellR6C2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR6C2 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''hlR6C2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlR6C2 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''cellR6C3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR6C3 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''hlR6C3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlR6C3 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''cellR6C4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR6C4 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''hlR6C4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlR6C4 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''cellR6C5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR6C5 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''hlR6C5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlR6C5 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''cellR6C6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR6C6 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''hlR6C6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlR6C6 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''cellR6C7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR6C7 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''hlR6C7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlR6C7 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''row7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents row7 As Global.System.Web.UI.WebControls.TableRow
    
    '''<summary>
    '''cellR7C1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR7C1 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''hlR7C1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlR7C1 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''cellR7C2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR7C2 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''hlR7C2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlR7C2 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''cellR7C3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR7C3 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''hlR7C3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlR7C3 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''cellR7C4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR7C4 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''hlR7C4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlR7C4 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''cellR7C5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR7C5 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''hlR7C5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlR7C5 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''cellR7C6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR7C6 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''hlR7C6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlR7C6 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''cellR7C7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR7C7 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''hlR7C7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlR7C7 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''row8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents row8 As Global.System.Web.UI.WebControls.TableRow
    
    '''<summary>
    '''cellR8C1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR8C1 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''hlR8C1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlR8C1 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''cellR8C2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR8C2 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''hlR8C2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlR8C2 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''cellR8C3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR8C3 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''hlR8C3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlR8C3 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''cellR8C4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR8C4 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''hlR8C4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlR8C4 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''cellR8C5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR8C5 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''hlR8C5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlR8C5 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''cellR8C6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR8C6 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''hlR8C6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlR8C6 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''cellR8C7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR8C7 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''hlR8C7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlR8C7 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''row9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents row9 As Global.System.Web.UI.WebControls.TableRow
    
    '''<summary>
    '''cellR9C1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR9C1 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''hlR9C1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlR9C1 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''cellR9C2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR9C2 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''hlR9C2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlR9C2 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''cellR9C3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR9C3 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''hlR9C3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlR9C3 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''cellR9C4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR9C4 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''hlR9C4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlR9C4 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''cellR9C5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR9C5 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''hlR9C5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlR9C5 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''cellR9C6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR9C6 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''hlR9C6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlR9C6 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''cellR9C7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR9C7 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''hlR9C7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlR9C7 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''row10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents row10 As Global.System.Web.UI.WebControls.TableRow
    
    '''<summary>
    '''cellR10C1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR10C1 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''hlR10C1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlR10C1 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''cellR10C2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR10C2 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''hlR10C2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlR10C2 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''cellR10C3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR10C3 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''hlR10C3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlR10C3 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''cellR10C4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR10C4 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''hlR10C4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlR10C4 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''cellR10C5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR10C5 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''hlR10C5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlR10C5 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''cellR10C6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR10C6 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''hlR10C6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlR10C6 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''cellR10C7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR10C7 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''hlR10C7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlR10C7 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''row11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents row11 As Global.System.Web.UI.WebControls.TableRow
    
    '''<summary>
    '''cellR11C1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR11C1 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''hlR11C1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlR11C1 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''cellR11C2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR11C2 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''hlR11C2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlR11C2 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''cellR11C3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR11C3 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''hlR11C3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlR11C3 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''cellR11C4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR11C4 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''hlR11C4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlR11C4 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''cellR11C5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR11C5 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''hlR11C5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlR11C5 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''cellR11C6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR11C6 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''hlR11C6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlR11C6 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''cellR11C7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR11C7 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''hlR11C7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlR11C7 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''row12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents row12 As Global.System.Web.UI.WebControls.TableRow
    
    '''<summary>
    '''cellR12C1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR12C1 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''hlR12C1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlR12C1 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''cellR12C2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR12C2 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''hlR12C2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlR12C2 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''cellR12C3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR12C3 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''hlR12C3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlR12C3 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''cellR12C4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR12C4 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''hlR12C4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlR12C4 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''cellR12C5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR12C5 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''hlR12C5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlR12C5 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''cellR12C6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR12C6 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''hlR12C6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlR12C6 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''cellR12C7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cellR12C7 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''hlR12C7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlR12C7 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''tblBKPlayoffMatchup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblBKPlayoffMatchup As Global.System.Web.UI.WebControls.Table
    
    '''<summary>
    '''lblTeam1SeasonInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTeam1SeasonInfo As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblTeam2SeasonInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTeam2SeasonInfo As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''RadGridTeamSeason control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadGridTeamSeason As Global.Telerik.Web.UI.RadGrid
    
    '''<summary>
    '''RadGridTeamHistory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadGridTeamHistory As Global.Telerik.Web.UI.RadGrid
    
    '''<summary>
    '''hlBottom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlBottom As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''SqlDataSource1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource1 As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''SqlDataSource2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource2 As Global.System.Web.UI.WebControls.SqlDataSource
End Class
