'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Schools

	'''<summary>
	'''RadAjaxPanel2 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents RadAjaxPanel2 As Global.Telerik.Web.UI.RadAjaxPanel

	'''<summary>
	'''RadPageLayout1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents RadPageLayout1 As Global.Telerik.Web.UI.RadPageLayout

	'''<summary>
	'''RadRotator1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents RadRotator1 As Global.Telerik.Web.UI.RadRotator

	'''<summary>
	'''lblScroller1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblScroller1 As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''lblScroller2 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblScroller2 As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''SqlDataSourceArticles control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents SqlDataSourceArticles As Global.System.Web.UI.WebControls.SqlDataSource

	'''<summary>
	'''RadPageLayout21 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents RadPageLayout21 As Global.Telerik.Web.UI.RadPageLayout

	'''<summary>
	'''imgAllDecade control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents imgAllDecade As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''GridView0 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents GridView0 As Global.System.Web.UI.WebControls.GridView

	'''<summary>
	'''GridView1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents GridView1 As Global.System.Web.UI.WebControls.GridView

	'''<summary>
	'''GridView2 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents GridView2 As Global.System.Web.UI.WebControls.GridView

	'''<summary>
	'''RadGrid1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents RadGrid1 As Global.Telerik.Web.UI.RadGrid

	'''<summary>
	'''SqlDataSource1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents SqlDataSource1 As Global.System.Web.UI.WebControls.SqlDataSource
End Class
