'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class StateChampionshipsBySchool

    '''<summary>
    '''RadAjaxPanel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAjaxPanel2 As Global.Telerik.Web.UI.RadAjaxPanel

    '''<summary>
    '''RadPageLayout1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadPageLayout1 As Global.Telerik.Web.UI.RadPageLayout

    '''<summary>
    '''lblOneColumnHeader0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOneColumnHeader0 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblOneColumnDetail0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOneColumnDetail0 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblOneColumnHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOneColumnHeader As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblOneColumnDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOneColumnDetail As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''RadAjaxPanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAjaxPanel1 As Global.Telerik.Web.UI.RadAjaxPanel

    '''<summary>
    '''tblSCBySchool control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblSCBySchool As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''rowSportsPage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowSportsPage As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''cmdCloseSportsPage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdCloseSportsPage As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''ucSportsPage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ucSportsPage As Global.TheSportsEngine2017.ucSportsPage

    '''<summary>
    '''RadDropDownListSchools control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadDropDownListSchools As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInfo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''rowBaseball control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowBaseball As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''rowBaseballYears control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowBaseballYears As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''rowBaseballFall control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowBaseballFall As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''rowBaseballFallYears control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowBaseballFallYears As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''rowBasketballBoys control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowBasketballBoys As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''rowBasketballBoysYears control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowBasketballBoysYears As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''rowBasketballGirls control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowBasketballGirls As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''rowBasketballGirlsYears control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowBasketballGirlsYears As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''rowFootball control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowFootball As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''rowFootballYears control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowFootballYears As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''rowFPSoftball control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowFPSoftball As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''rowFPSoftballYears control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowFPSoftballYears As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''rowSPSoftball control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowSPSoftball As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''rowSPSoftballYears control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowSPSoftballYears As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''rowCheerleading control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowCheerleading As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''rowCheerleadingYears control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowCheerleadingYears As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''rowCrossCountryBoys control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowCrossCountryBoys As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''rowCrossCountryBoysYears control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowCrossCountryBoysYears As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''rowCrossCountryGirls control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowCrossCountryGirls As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''rowCrossCountryGirlsYears control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowCrossCountryGirlsYears As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''rowGolfBoys control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowGolfBoys As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''rowGolfBoysYears control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowGolfBoysYears As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''rowGolfGirls control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowGolfGirls As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''rowGolfGirlsYears control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowGolfGirlsYears As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''rowSoccerBoys control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowSoccerBoys As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''rowSoccerBoysYears control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowSoccerBoysYears As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''rowSoccerGirls control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowSoccerGirls As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''rowSoccerGirlsYears control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowSoccerGirlsYears As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''rowSwimmingBoys control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowSwimmingBoys As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''rowSwimmingBoysYears control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowSwimmingBoysYears As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''rowSwimmingGirls control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowSwimmingGirls As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''rowSwimmingGirlsYears control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowSwimmingGirlsYears As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''rowTennisBoys control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowTennisBoys As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''rowTennisBoysYears control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowTennisBoysYears As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''rowTennisGirls control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowTennisGirls As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''rowTennisGirlsYears control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowTennisGirlsYears As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''rowTrackBoys control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowTrackBoys As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''rowTrackBoysYears control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowTrackBoysYears As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''rowTrackGirls control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowTrackGirls As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''rowTrackGirlsYears control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowTrackGirlsYears As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''rowVolleyball control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowVolleyball As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''rowVolleyballYears control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowVolleyballYears As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''rowWrestling control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowWrestling As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''rowWrestlingYears control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowWrestlingYears As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''rowWrestlingDual control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowWrestlingDual As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''rowWrestlingDualYears control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowWrestlingDualYears As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''rowJazzBand control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowJazzBand As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''rowJazzBandYears control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowJazzBandYears As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''rowSpeechDebate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowSpeechDebate As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''rowSpeechDebateYears control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowSpeechDebateYears As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''rowOneAct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowOneAct As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''rowOneActYears control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowOneActYears As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''rowAdBottom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowAdBottom As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''hlBottom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlBottom As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''SqlDataSourceSchools control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceSchools As Global.System.Web.UI.WebControls.SqlDataSource
End Class
